### ISSUE TITLE
Option for override using Keyboard

### ISSUE THREAD

**Issue by HatBeardMe** [hensm/disable_tab_detach#6]
I see in the last commit https://github.com/hensm/disable_tab_detach/commit/38d428b5ff7683e7fc2f8028d30b269dfe18c0bc you've disabled the plugin if multiple tabs are selected. Appreciated.

Can you add a keyboard override as well? Like if `shift` is held down you can tear a single tab away? Or a keyboard shortcut that will pop the current tab to a new window?

**Comment by hensm** [comment]
This is what I have in a local branch:

![screenshot 2019-02-14 at 06 33 14](https://user-images.githubusercontent.com/6956633/52767451-7a46ea80-3022-11e9-91e2-3bd792064b68.png)


Can't do modifier keys due to limitations of the extension API, but there's a command (Ctrl+Alt+N) that moves the current tab to a new window.

**Comment by hensm** [comment]
v0.0.4+:
`Ctrl`+`Alt`+`N` — Move tab to new window
`Ctrl`+`Alt`+`P` — Pause extension
